spring.datasource.url=jdbc:postgresql://localhost:14577/assem
spring.datasource.username=postgres
spring.datasource.password=foxx

assem.storage.registrations=storage

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
