#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap for the Asset Management System.
# Prepares PostgreSQL, the Spring Boot backend, and the Vue/Vite frontend.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PG_VERSION=16
PGBIN="/usr/lib/postgresql/${PG_VERSION}/bin"
export PGDATA="${PGDATA:-$HOME/pgdata}"
PGPORT=5432
PGSOCK=/tmp

# 1. Ensure the PostgreSQL server is installed.
if [ ! -x "$PGBIN/postgres" ]; then
  echo "==> Installing PostgreSQL ${PG_VERSION}"
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
fi

# 2. Initialize a self-contained cluster (owned by the current user, so no sudo
#    is needed to run it). scram for TCP, trust for the local socket.
if [ ! -s "$PGDATA/PG_VERSION" ]; then
  echo "==> Initializing PostgreSQL cluster at $PGDATA"
  rm -rf "$PGDATA"
  mkdir -p "$PGDATA"
  pwfile="$(mktemp)"
  echo "postgres" > "$pwfile"
  "$PGBIN/initdb" -U postgres --auth-local=trust --auth-host=scram-sha-256 \
    --pwfile="$pwfile" -D "$PGDATA" >/dev/null
  rm -f "$pwfile"
fi

# 3. Start the server (idempotent) so we can create/seed the database.
if ! "$PGBIN/pg_ctl" -D "$PGDATA" status >/dev/null 2>&1; then
  echo "==> Starting PostgreSQL"
  "$PGBIN/pg_ctl" -D "$PGDATA" -l "$HOME/pg.log" -o "-p $PGPORT -k $PGSOCK" -w start
fi

export PGPASSWORD=postgres
PSQL=("$PGBIN/psql" -U postgres -h localhost -p "$PGPORT")

# 4. Create and seed the 'assem' database only if it does not exist yet.
if ! "${PSQL[@]}" -lqt | cut -d '|' -f1 | grep -qw assem; then
  echo "==> Creating and seeding the 'assem' database"
  "$PGBIN/createdb" -U postgres -h localhost -p "$PGPORT" assem
  # asset_management.sql was produced by pg_dump 17; 'transaction_timeout' is a
  # PostgreSQL 17 setting the 16 server does not recognize, so drop that line.
  sed '/^SET transaction_timeout/d' asset_management.sql \
    | "${PSQL[@]}" -d assem -v ON_ERROR_STOP=1 >/dev/null
  "${PSQL[@]}" -d assem -v ON_ERROR_STOP=1 -f .cursor/seed.sql >/dev/null
fi

# 5. Backend runtime config (gitignored). Points Spring at the local cluster and
#    allows the Vite dev origin through CORS.
if [ ! -f backend/config.properties ]; then
  echo "==> Writing backend/config.properties"
  cat > backend/config.properties <<'PROPS'
# Generated by .cursor/install.sh for local Cloud Agent development.
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/assem
spring.datasource.username=postgres
spring.datasource.password=postgres

# The Vite dev server (http://localhost:5173) proxies /api -> :8080 with
# changeOrigin, so the browser Origin differs from the rewritten Host and Spring
# treats requests as cross-origin. List the dev origin so CORS passes.
assem.cors.allowed-origins=http://localhost:5173

assem.storage.registrations=storage

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
PROPS
fi

# 6. Build the backend (also warms the Maven cache).
echo "==> Building backend"
( cd backend && chmod +x mvnw && ./mvnw -q -DskipTests clean package )

# 7. Install frontend dependencies.
echo "==> Installing frontend dependencies"
( cd frontend && npm ci )

echo "==> install complete"
